"""Adicionado cores Agenda

Revision ID: 22841a23b8af
Revises: f0d9e909e69e
Create Date: 2025-04-30 21:57:57.075813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22841a23b8af'
down_revision = 'f0d9e909e69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
