"""Atualizado CPF e CNPJ

Revision ID: 288022e951d9
Revises: 34fc493f0078
Create Date: 2025-04-23 21:28:35.708088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288022e951d9'
down_revision = '34fc493f0078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('clientes_cnpj_key', type_='unique')
        batch_op.drop_constraint('clientes_cpf_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint('clientes_cpf_key', ['cpf'])
        batch_op.create_unique_constraint('clientes_cnpj_key', ['cnpj'])

    # ### end Alembic commands ###
