"""Adicionando tabela vendedores

Revision ID: 34fc493f0078
Revises: 774166131359
Create Date: 2025-04-23 20:30:19.260210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fc493f0078'
down_revision = '774166131359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedores')
    # ### end Alembic commands ###
