"""Initial tables

Revision ID: 437bb5c85a89
Revises: 
Create Date: 2025-05-11 21:45:03.765489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437bb5c85a89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cidade', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('cpf', sa.TEXT(), nullable=False),
    sa.Column('cnpj', sa.TEXT(), nullable=False),
    sa.Column('vendedor', sa.TEXT(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('localizacao', sa.TEXT(), nullable=False),
    sa.Column('situacao', sa.TEXT(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('consultor', sa.TEXT(), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario', sa.TEXT(), nullable=False),
    sa.Column('nome_cliente', sa.TEXT(), nullable=False),
    sa.Column('equipamento', sa.TEXT(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('onu', sa.TEXT(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rede_wifi', sa.TEXT(), nullable=False),
    sa.Column('senha_wifi', sa.TEXT(), nullable=False),
    sa.Column('teste', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('cidade', sa.TEXT(), nullable=False),
    sa.Column('tipo', sa.TEXT(), nullable=False),
    sa.Column('faturado', sa.TEXT(), nullable=False),
    sa.Column('nota_fiscal', sa.TEXT(), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_equipamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_equipamento', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_login',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario', sa.TEXT(), nullable=False),
    sa.Column('senha', sa.TEXT(), nullable=False),
    sa.Column('tipo', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('titulo', sa.TEXT(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=False),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('cidade_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('usuarios_login')
    op.drop_table('tipo_equipamento')
    op.drop_table('equipamentos')
    op.drop_table('clientes')
    op.drop_table('cidades')
    # ### end Alembic commands ###
