"""Adicionar tabela cidades

Revision ID: 5deb98b00080
Revises: 288022e951d9
Create Date: 2025-04-23 21:33:58.798778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5deb98b00080'
down_revision = '288022e951d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cidade', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cidades')
    # ### end Alembic commands ###
