"""Adicionado equipamentos e tipos de equipamentos

Revision ID: 6394aee8fd1d
Revises: 5deb98b00080
Create Date: 2025-04-25 22:02:20.024368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6394aee8fd1d'
down_revision = '5deb98b00080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario', sa.TEXT(), nullable=False),
    sa.Column('nome_cliente', sa.TEXT(), nullable=False),
    sa.Column('equipamento', sa.TEXT(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('onu', sa.TEXT(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rede_wifi', sa.TEXT(), nullable=False),
    sa.Column('senha_wifi', sa.TEXT(), nullable=False),
    sa.Column('teste', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('cidade', sa.TEXT(), nullable=False),
    sa.Column('tipo', sa.TEXT(), nullable=False),
    sa.Column('faturado', sa.TEXT(), nullable=False),
    sa.Column('nota_fiscal', sa.TEXT(), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_equipamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_equipamento', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_equipamento')
    op.drop_table('equipamentos')
    # ### end Alembic commands ###
