"""init

Revision ID: 774166131359
Revises: 
Create Date: 2025-04-16 21:39:18.086771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774166131359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('cpf', sa.TEXT(), nullable=False),
    sa.Column('cnpj', sa.TEXT(), nullable=False),
    sa.Column('vendedor', sa.TEXT(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('localizacao', sa.TEXT(), nullable=False),
    sa.Column('situacao', sa.TEXT(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('consultor', sa.TEXT(), nullable=False),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
