"""Adicionado cidades na agenda

Revision ID: 774dcc27c5e4
Revises: 22841a23b8af
Create Date: 2025-04-30 23:03:05.555741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774dcc27c5e4'
down_revision = '22841a23b8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('titulo', sa.TEXT(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=False),
    sa.Column('color', sa.TEXT(), nullable=True),
    sa.Column('cidade_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
