"""Ajustado login

Revision ID: de2032731286
Revises: 6394aee8fd1d
Create Date: 2025-04-26 01:08:13.290115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2032731286'
down_revision = '6394aee8fd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_login',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario', sa.TEXT(), nullable=False),
    sa.Column('senha', sa.TEXT(), nullable=False),
    sa.Column('tipo', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_login')
    # ### end Alembic commands ###
