"""Apagado vendedores

Revision ID: e09ba7453154
Revises: de2032731286
Create Date: 2025-04-29 23:41:49.598356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09ba7453154'
down_revision = 'de2032731286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vendedores_pkey'),
    sa.UniqueConstraint('nome', name='vendedores_nome_key')
    )
    # ### end Alembic commands ###
