"""Initial tables

Revision ID: e51447367ad9
Revises: 437bb5c85a89
Create Date: 2025-05-21 20:06:22.625577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e51447367ad9'
down_revision = '437bb5c85a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_login', schema=None) as batch_op:
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###
