"""Adicionado Agenda

Revision ID: f0d9e909e69e
Revises: e09ba7453154
Create Date: 2025-04-30 21:33:08.220177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d9e909e69e'
down_revision = 'e09ba7453154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('titulo', sa.TEXT(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
